In [619]:
import pandas as pd

df=pd.read_csv('Large_dataset.csv') #reading the csv file

In [620]:
#Initial Data Checking
df.head()

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,0,riya,NaN,116530,NaN,riya48@gmail.com,2023/04/20
1,139,rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,2,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,3,riya,-3.0,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,58,Karan,NaN,112349,Delhi,karan43@gmail.com,2023-01-15

In [621]:
df.tail()

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
295,11,karan,-3.0,Not Available,Mumbai,karan29@gmail.com,NaN
296,88,anjali,54.0,39808,Delhi,anjali43@gmail.com,2023/04/20
297,121,Simran,0.0,-10000,Kolkata,simran16@gmail.com,2023-01-15
298,298,Rohit,NaN,-10000,Mumbai,rohit11@gmail.com,15/02/2023
299,299,Aman,NaN,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [622]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   300 non-null    int64
 1   Name         300 non-null    object
 2   Age          225 non-null    float64
 3   Salary       227 non-null    object
 4   City         251 non-null    object
 5   Email        300 non-null    object
 6   JoiningDate  234 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 16.5+ KB

In [623]:
#fixing the unsorted column and initializing a new column to it using reset_index

In [624]:
#Fix CustomerID first
clean_data=df

In [625]:
clean_data=df.reset_index(drop=True)
clean_data['CustomerID']=clean_data.index +1 #index start from 1

In [626]:
#Standardizing text values

In [627]:
#Fix Name
clean_data['Name']=clean_data['Name'].str.strip() #remove extra space
clean_data['Name']=clean_data['Name'].str.title() #make the first word capital
clean_data

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,Riya,NaN,116530,NaN,riya48@gmail.com,2023/04/20
1,2,Rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,3,Anjali,NaN,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,4,Riya,-3.0,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,5,Karan,NaN,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,296,Karan,-3.0,Not Available,Mumbai,karan29@gmail.com,NaN
296,297,Anjali,54.0,39808,Delhi,anjali43@gmail.com,2023/04/20
297,298,Simran,0.0,-10000,Kolkata,simran16@gmail.com,2023-01-15
298,299,Rohit,NaN,-10000,Mumbai,rohit11@gmail.com,15/02/2023
299,300,Aman,NaN,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [628]:
#Cleaning the age column

In [629]:
clean_data['Age']=clean_data['Age'].abs()
[clean_data['Age']<18] #LESS 18 IS 157
[clean_data['Age']>18] #GREATER THAN 18 IS 67
#75 null value and invalid age 157

[0      False
 1       True
 2      False
 3      False
 4      False
        ...
 295    False
 296     True
 297    False
 298    False
 299    False
 Name: Age, Length: 300, dtype: bool]

In [630]:
clean_data.loc[clean_data['Age']<18 ,'Age']=None #those who are less then 18 are not valid so converting them to Nan
avg=clean_data['Age'].mean() #getting the average age
avg#avg is 39

np.float64(39.0)

In [631]:
clean_data['Age']=clean_data['Age'].fillna(avg) #replacing Nan with avg age
clean_data

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,Riya,39.0,116530,NaN,riya48@gmail.com,2023/04/20
1,2,Rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,3,Anjali,39.0,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,4,Riya,39.0,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,5,Karan,39.0,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,296,Karan,39.0,Not Available,Mumbai,karan29@gmail.com,NaN
296,297,Anjali,54.0,39808,Delhi,anjali43@gmail.com,2023/04/20
297,298,Simran,39.0,-10000,Kolkata,simran16@gmail.com,2023-01-15
298,299,Rohit,39.0,-10000,Mumbai,rohit11@gmail.com,15/02/2023
299,300,Aman,39.0,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [632]:
clean_data

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,Riya,39.0,116530,NaN,riya48@gmail.com,2023/04/20
1,2,Rohit,32.0,NaN,NaN,rohit42@gmail.com,15/02/2023
2,3,Anjali,39.0,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,4,Riya,39.0,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,5,Karan,39.0,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,296,Karan,39.0,Not Available,Mumbai,karan29@gmail.com,NaN
296,297,Anjali,54.0,39808,Delhi,anjali43@gmail.com,2023/04/20
297,298,Simran,39.0,-10000,Kolkata,simran16@gmail.com,2023-01-15
298,299,Rohit,39.0,-10000,Mumbai,rohit11@gmail.com,15/02/2023
299,300,Aman,39.0,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [633]:
clean_data['Age']=clean_data['Age'].astype(int)
clean_data

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,Riya,39,116530,NaN,riya48@gmail.com,2023/04/20
1,2,Rohit,32,NaN,NaN,rohit42@gmail.com,15/02/2023
2,3,Anjali,39,-10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,4,Riya,39,-10000,Kolkata,riya8@gmail.com,2023/04/20
4,5,Karan,39,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,296,Karan,39,Not Available,Mumbai,karan29@gmail.com,NaN
296,297,Anjali,54,39808,Delhi,anjali43@gmail.com,2023/04/20
297,298,Simran,39,-10000,Kolkata,simran16@gmail.com,2023-01-15
298,299,Rohit,39,-10000,Mumbai,rohit11@gmail.com,15/02/2023
299,300,Aman,39,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [634]:
#fixing salary
clean_data['Salary'].mode() 
clean_data['Salary']=pd.to_numeric(clean_data['Salary'], errors='coerce') #converting the type to int/float and non numerice to Nan

In [635]:

clean_data['Salary']=clean_data['Salary'].abs()

In [636]:
avg_sal=clean_data['Salary'].mean() #avg salary 38273
clean_data

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,Riya,39,116530.0,NaN,riya48@gmail.com,2023/04/20
1,2,Rohit,32,NaN,NaN,rohit42@gmail.com,15/02/2023
2,3,Anjali,39,10000.0,Chandigarh,anjali18@gmail.com,March 10 2023
3,4,Riya,39,10000.0,Kolkata,riya8@gmail.com,2023/04/20
4,5,Karan,39,112349.0,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,296,Karan,39,NaN,Mumbai,karan29@gmail.com,NaN
296,297,Anjali,54,39808.0,Delhi,anjali43@gmail.com,2023/04/20
297,298,Simran,39,10000.0,Kolkata,simran16@gmail.com,2023-01-15
298,299,Rohit,39,10000.0,Mumbai,rohit11@gmail.com,15/02/2023
299,300,Aman,39,NaN,Kolkata,aman17@gmail.com,2023-01-15

In [637]:
clean_data['Salary']=clean_data['Salary'].fillna(avg_sal)
clean_data

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,Riya,39,116530.00,NaN,riya48@gmail.com,2023/04/20
1,2,Rohit,32,38273.75,NaN,rohit42@gmail.com,15/02/2023
2,3,Anjali,39,10000.00,Chandigarh,anjali18@gmail.com,March 10 2023
3,4,Riya,39,10000.00,Kolkata,riya8@gmail.com,2023/04/20
4,5,Karan,39,112349.00,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,296,Karan,39,38273.75,Mumbai,karan29@gmail.com,NaN
296,297,Anjali,54,39808.00,Delhi,anjali43@gmail.com,2023/04/20
297,298,Simran,39,10000.00,Kolkata,simran16@gmail.com,2023-01-15
298,299,Rohit,39,10000.00,Mumbai,rohit11@gmail.com,15/02/2023
299,300,Aman,39,38273.75,Kolkata,aman17@gmail.com,2023-01-15

In [638]:
clean_data['Salary']=clean_data['Salary'].astype(int)

clean_data

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,Riya,39,116530,NaN,riya48@gmail.com,2023/04/20
1,2,Rohit,32,38273,NaN,rohit42@gmail.com,15/02/2023
2,3,Anjali,39,10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,4,Riya,39,10000,Kolkata,riya8@gmail.com,2023/04/20
4,5,Karan,39,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,296,Karan,39,38273,Mumbai,karan29@gmail.com,NaN
296,297,Anjali,54,39808,Delhi,anjali43@gmail.com,2023/04/20
297,298,Simran,39,10000,Kolkata,simran16@gmail.com,2023-01-15
298,299,Rohit,39,10000,Mumbai,rohit11@gmail.com,15/02/2023
299,300,Aman,39,38273,Kolkata,aman17@gmail.com,2023-01-15

In [639]:
#using Quantile to see outliers in the dataset

In [640]:
#quantile to see outiers in salary
q1=clean_data['Salary'].quantile(0.45)
q3=clean_data['Salary'].quantile(0.95)
iqr= q3-q1 #tell the total spread of the middle values in the dataset
lower=q1-1.5 *iqr
upper =q3+1.5*iqr
clean_data[(clean_data['Salary']>=lower) & (clean_data['Salary']<=upper)] #thats means our data have no outlier in salary

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,Riya,39,116530,NaN,riya48@gmail.com,2023/04/20
1,2,Rohit,32,38273,NaN,rohit42@gmail.com,15/02/2023
2,3,Anjali,39,10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,4,Riya,39,10000,Kolkata,riya8@gmail.com,2023/04/20
4,5,Karan,39,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,296,Karan,39,38273,Mumbai,karan29@gmail.com,NaN
296,297,Anjali,54,39808,Delhi,anjali43@gmail.com,2023/04/20
297,298,Simran,39,10000,Kolkata,simran16@gmail.com,2023-01-15
298,299,Rohit,39,10000,Mumbai,rohit11@gmail.com,15/02/2023
299,300,Aman,39,38273,Kolkata,aman17@gmail.com,2023-01-15

In [641]:
clean_data['City'].info() #49 null-values type is correct

<class 'pandas.core.series.Series'>
RangeIndex: 300 entries, 0 to 299
Series name: City
Non-Null Count  Dtype
--------------  -----
251 non-null    object
dtypes: object(1)
memory usage: 2.5+ KB

In [642]:
clean_data['City']=clean_data['City'].str.strip()
clean_data['City']=clean_data['City'].str.title()
clean_data

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,Riya,39,116530,NaN,riya48@gmail.com,2023/04/20
1,2,Rohit,32,38273,NaN,rohit42@gmail.com,15/02/2023
2,3,Anjali,39,10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,4,Riya,39,10000,Kolkata,riya8@gmail.com,2023/04/20
4,5,Karan,39,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,296,Karan,39,38273,Mumbai,karan29@gmail.com,NaN
296,297,Anjali,54,39808,Delhi,anjali43@gmail.com,2023/04/20
297,298,Simran,39,10000,Kolkata,simran16@gmail.com,2023-01-15
298,299,Rohit,39,10000,Mumbai,rohit11@gmail.com,15/02/2023
299,300,Aman,39,38273,Kolkata,aman17@gmail.com,2023-01-15

In [643]:
clean_data['City'].isnull().sum() #49
clean_data['City']=clean_data['City'].fillna("Unknown")
clean_data

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,Riya,39,116530,Unknown,riya48@gmail.com,2023/04/20
1,2,Rohit,32,38273,Unknown,rohit42@gmail.com,15/02/2023
2,3,Anjali,39,10000,Chandigarh,anjali18@gmail.com,March 10 2023
3,4,Riya,39,10000,Kolkata,riya8@gmail.com,2023/04/20
4,5,Karan,39,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,296,Karan,39,38273,Mumbai,karan29@gmail.com,NaN
296,297,Anjali,54,39808,Delhi,anjali43@gmail.com,2023/04/20
297,298,Simran,39,10000,Kolkata,simran16@gmail.com,2023-01-15
298,299,Rohit,39,10000,Mumbai,rohit11@gmail.com,15/02/2023
299,300,Aman,39,38273,Kolkata,aman17@gmail.com,2023-01-15

In [644]:
clean_data['Email'].info()
clean_data['Email'].str.strip()
clean_data['Email'].str.lower()

<class 'pandas.core.series.Series'>
RangeIndex: 300 entries, 0 to 299
Series name: Email
Non-Null Count  Dtype
--------------  -----
300 non-null    object
dtypes: object(1)
memory usage: 2.5+ KB

0        riya48@gmail.com
1       rohit42@gmail.com
2      anjali18@gmail.com
3         riya8@gmail.com
4       karan43@gmail.com
              ...
295     karan29@gmail.com
296    anjali43@gmail.com
297    simran16@gmail.com
298     rohit11@gmail.com
299      aman17@gmail.com
Name: Email, Length: 300, dtype: object

In [ ]:
#Cleaning dates

In [645]:
clean_data['JoiningDate'].str.strip()

0         2023/04/20
1         15/02/2023
2      March 10 2023
3         2023/04/20
4         2023-01-15
           ...
295              NaN
296       2023/04/20
297       2023-01-15
298       15/02/2023
299       2023-01-15
Name: JoiningDate, Length: 300, dtype: object

In [646]:
print(clean_data['JoiningDate'].unique()) # getting unique dates

['2023/04/20' '15/02/2023' 'March 10 2023' '2023-01-15' nan]

In [648]:

clean_data['JoiningDate'] = clean_data['JoiningDate'].str.replace(
    'March 10 2023', '03-10-2023'
)

In [649]:
clean_data['JoiningDate'] = clean_data['JoiningDate'].str.replace(
 '15/02/2023', '15-02-2023'
)

In [650]:
clean_data['JoiningDate'] = clean_data['JoiningDate'].str.replace(
 '2023-01-15', '15-01-2023'
)

In [651]:
clean_data['JoiningDate'] = clean_data['JoiningDate'].str.replace(
'2023/04/20' , '20-04-2023'
)

In [652]:
clean_data['JoiningDate'].unique()

array(['20-04-2023', '15-02-2023', '03-10-2023', '15-01-2023', nan],
      dtype=object)

In [653]:
clean_data['JoiningDate']=pd.to_datetime(clean_data['JoiningDate'], errors='coerce',dayfirst=False) # changing the type of date

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18352\2363132708.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  clean_data['JoiningDate']=pd.to_datetime(clean_data['JoiningDate'], errors='coerce',dayfirst=False)

In [654]:
clean_data

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,Riya,39,116530,Unknown,riya48@gmail.com,2023-04-20
1,2,Rohit,32,38273,Unknown,rohit42@gmail.com,2023-02-15
2,3,Anjali,39,10000,Chandigarh,anjali18@gmail.com,2023-10-03
3,4,Riya,39,10000,Kolkata,riya8@gmail.com,2023-04-20
4,5,Karan,39,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,296,Karan,39,38273,Mumbai,karan29@gmail.com,NaT
296,297,Anjali,54,39808,Delhi,anjali43@gmail.com,2023-04-20
297,298,Simran,39,10000,Kolkata,simran16@gmail.com,2023-01-15
298,299,Rohit,39,10000,Mumbai,rohit11@gmail.com,2023-02-15
299,300,Aman,39,38273,Kolkata,aman17@gmail.com,2023-01-15

In [655]:
clean_data['JoiningDate'].isnull().sum() # getting the sum of null dates

np.int64(66)

In [656]:
#Using mode get the most frequent date and replace the null

In [657]:
clean_data['JoiningDate'].mode() #2023-04-20

0   2023-04-20
Name: JoiningDate, dtype: datetime64[ns]

In [658]:
clean_data['JoiningDate'] = clean_data['JoiningDate'].fillna(pd.Timestamp('2023-04-20')) #replacing the null

In [659]:
clean_data

,CustomerID,Name,Age,Salary,City,Email,JoiningDate
0,1,Riya,39,116530,Unknown,riya48@gmail.com,2023-04-20
1,2,Rohit,32,38273,Unknown,rohit42@gmail.com,2023-02-15
2,3,Anjali,39,10000,Chandigarh,anjali18@gmail.com,2023-10-03
3,4,Riya,39,10000,Kolkata,riya8@gmail.com,2023-04-20
4,5,Karan,39,112349,Delhi,karan43@gmail.com,2023-01-15
...,...,...,...,...,...,...,...
295,296,Karan,39,38273,Mumbai,karan29@gmail.com,2023-04-20
296,297,Anjali,54,39808,Delhi,anjali43@gmail.com,2023-04-20
297,298,Simran,39,10000,Kolkata,simran16@gmail.com,2023-01-15
298,299,Rohit,39,10000,Mumbai,rohit11@gmail.com,2023-02-15
299,300,Aman,39,38273,Kolkata,aman17@gmail.com,2023-01-15

In [661]:
clean_data.to_excel('cleaned_data.xlsx', index=False)

In [662]:
import os
print(os.getcwd())

C:\Users\Lenovo

In [663]:
os.listdir()

['.anaconda',
 '.android',
 '.conda',
 '.continuum',
 '.copilot',
 '.gradle',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.python_history',
 '.skiko',
 '.vscode',
 'aanya bisht - Shortcut.lnk',
 'ai',
 'anaconda3',
 'anaconda_projects',
 'AndroidStudioProjects',
 'AppData',
 'Application Data',
 'automaticSystem.zip',
 'basic.ipynb',
 'cec-events.zip',
 'cleaned_data.xlsx',
 'Contacts',
 'Cookies',
 'dataCleaned.ipynb',
 'DataCleaning',
 'dataCleaningPrac.ipynb',
 'DataPy.pdf',
 'demo.csv',
 'desktop.ini',
 'Documents',
 'Downloads',
 'drivingImage.jpg',
 'Excel_Pivot_Dashboard',
 'Fake.csv',
 'fakeNews.ipynb',
 'fakeNews.txt',
 'fake_name',
 'Favorites',
 'Large_dataset.csv',
 'Links',
 'Local Settings',
 'MachineLearning.ipynb',
 'megaProject1',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{d912ce5a-1795-11f1-af96-c9f4fcd8d630}.TxR.0.regtrans-ms',
 'NTUSER.DAT{d912ce5a-1795-11f1-af96-c9f4fcd8d630}.TxR.1.regtrans-ms',
 'NTUSER.DAT{d912ce5a-1795-11f1-af96-c9f4fcd8d630}.TxR.2.regtrans-ms',
 'NTUSER.DAT{d912ce5a-1795-11f1-af96-c9f4fcd8d630}.TxR.blf',
 'NTUSER.DAT{d912ce5b-1795-11f1-af96-c9f4fcd8d630}.TM.blf',
 'NTUSER.DAT{d912ce5b-1795-11f1-af96-c9f4fcd8d630}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{d912ce5b-1795-11f1-af96-c9f4fcd8d630}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'Numpy.ipynb',
 'OneDrive',
 'Pandas.ipynb',
 'Pictures',
 'Portfolio',
 'practice',
 'PrintHood',
 'pyhtonDa',
 'PyMachine',
 'pyPanda',
 'Python',
 'python.ipynb',
 'pythonprac',
 'Recent',
 'SalesPivotData.csv',
 'Saved Games',
 'Searches',
 'SendTo',
 'source',
 'sql_dataCleaning_project',
 'Start Menu',
 'Templates',
 'True.csv',
 'Untitled Folder',
 'Untitled.ipynb',
 'untitled.txt',
 'Untitled1.ipynb',
 'untitled1.txt',
 'Untitled2.ipynb',
 'Videos',
 'Web']